on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all    
    steps:        
      - uses: actions/checkout@v4
      - run: npm ci
      - run: node ./index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}